[sources.log_kafka]
type = "kafka"
bootstrap_servers = "PLAINTEXT://redpanda:29092"
group_id = "vector-aggregator"
topics = ["log"]

[transforms.explode_logs]
type = "remap"
inputs = ["log_kafka"]
source = '''
_timestamp = to_unix_timestamp(to_timestamp!(.timestamp))
_namespace = ._namespace;
_msg = parse_json!(.message)
.message = _msg
raw_source = .
del(raw_source._namespace);
source = encode_json(.message)
raw_source = flatten!(.message)
. = {}

.string_names = []
.string_values = []
.number_names = []
.number_values = []
.bool_names = []
.bool_values = []
.array_values = []
.array_names = []

.accounts = []
.transactions = []
.checksum_addresses = []

for_each(array(keys(raw_source))) -> |_index, value| {
    v = get!(raw_source, [value]);
    if is_string(v){
        .string_names = push(.string_names, value)
        .string_values = push(.string_values, v)
    } else if is_integer(v) || is_float(v) {
        .number_names = push(.number_names, value)
        .number_values = push(.number_values, v)
    } else if is_boolean(v){
        .bool_names = push(.bool_names, value)
        .bool_values = push(.bool_values, v)
    } else if is_array(v){
        v = map_values(array!(v)) -> |vv| {
            if !is_object(vv) && !is_array(vv) || is_integer(v) || is_float(v) {
                to_string!(vv)
            } else {
                encode_json(vv)
            }
        }
        .array_names = push(.array_names, value)
        .array_values = push(.array_values, v)
    }
}

result, err = parse_regex_all(source, r'(?P<address>0x[0-9a-fA-F]{40})')
.accounts = unique(map_values(result) -> |value| { downcase!(get!(value, ["address"])) })

result, err = parse_regex_all(source, r'(?P<txhash>0x[0-9a-fA-F]{64})')
.transactions = unique(map_values(result) -> |value| { downcase!(get!(value, ["txhash"])) })

.source = source
._timestamp = _timestamp;
._namespace = _namespace
'''

[transforms.extract_keys]
type = "remap"
inputs = ["explode_logs"]
source = '''
string_names = if exists(.string_names) { .string_names } else { [] }
string_values = if exists(.string_values) { .string_values } else { [] }
number_names = if exists(.number_names) { .number_names } else { [] }
number_values = if exists(.number_values) { .number_values } else { [] }
bool_names = if exists(.bool_names) { .bool_names } else { [] }
bool_values = if exists(.bool_values) { .bool_values } else { [] }
array_names = if exists(.array_names) { .array_names } else { [] }
array_values = if exists(.array_values) { .array_values } else { [] }

. = {}
.key_types = []

for_each(array!(string_names)) -> |_index, value| {
    key_type = {}
    key_type.name = value
    key_type.type = "string"
    .key_types = push(.key_types, key_type)

}
for_each(array!(number_names)) -> |_index, value| {
    key_type = {}
    key_type.name = value
    key_type.type = "number"
    .key_types = push(.key_types, key_type)

}
for_each(array!(bool_names)) -> |_index, value| {
    key_type = {}
    key_type.name = value
    key_type.type = "boolean"
    .key_types = push(.key_types, key_type)
}
for_each(array!(array_names)) -> |_index, value| {
    key_type = {}
    key_type.name = value
    key_type.type = "array"
    .key_types = push(.key_types, key_type)
}

.namespace = if exists(._namespace) { ._namespace } else { "unknown" }

'''
[sinks.key_kafka]
type = "kafka"
inputs = ["extract_keys"]
bootstrap_servers = "PLAINTEXT://redpanda:29092"
topic = "log_key"
encoding.codec = "json"

[sinks.clickhouse]
inputs = ["explode_logs"]
type = "clickhouse"
endpoint = "http://clickhouse-server:8123"
table = "logs"

#[sinks.console]
#type = "console"
#inputs = ["extract_keys"]
#encoding.codec = "json"
